spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: gateway



springdoc:
  enable-native-support: true
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /v3/api-docs

        name: API Gateway Service

      - url: /user-service/v3/api-docs
        name: user Service

    oauth:
      client-secret: s73H0MEMDtCsOPqoX03pCh9O2wDd9KSc
      realm: microservices
      client-id: microservices
      use-basic-authentication-with-access-code-grant: true

    deep-linking: true



