spring:
  config:
    import: optional:configserver:http://localhost:8888?fail-fast=true&max-attempts=10&max-interval=1500&multiplier=1.2&initial-interval=1100

  application:
    name: blog-service

openapi:
  service:
    title: blog-service doc
    version: 1.0.0
    url: http://localhost:8222

springdoc:
  api-docs:
    path: /blog-service/v3/api-docs
  swagger-ui:
    path: /blog-service/swagger-ui.html