server:
  port: 8050
spring:
  # OAuth2 support can be enabled by adding the spring-boot-starter-oauth2-client dependency to your project and setting following flag:
  cloud:
    openfeign:
      oauth2:
         enabled: true

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/blogs
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect


application:
  config:
    user-url: http://localhost:8222/api/users
