server:
  port: 8222
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: lb:http://USER-SERVICE
          predicates:
            - Path=/api/users/** ,/user-service/v3/api-docs
          filters:
            # - RemoveRequestHeader=Authorization
            #- AddRequestHeader=Authorization, "Bearer  #{token}" # no need for this the gateway automitcally  send the token to the ms
        - id: blog-service
          uri: lb:http://BLOG-SERVICE
          predicates:
            - Path=/api/posts/** ,/blog-service/v3/api-docs
        - id: comments-service
          uri: lb:http://BLOG-SERVICE
          predicates:
            - Path=/api/comments/**

